services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app
      - JWT_SECRET_KEY=your_super_secret_key_for_jwt_tokens
    ports:
      - "8080:8000"
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
