{
 "title": "postgres",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Data info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read strings count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write strings count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update strings count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted strings count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "CPU work time (s)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"postgres-exporter:9187\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last scrape export time (s)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_exporter_last_scrape_duration_seconds{instance=\"postgres-exporter:9187\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database  status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  }
 ]
}